### ISSUE TITLE
Update statistic gathering to work with ledisdb

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#340]
The current way of aggregating statistics using lua script doesn't work properly with ledisdb.

While we can't use ledis for aggregation, idea is to move that logic in core-0 itself. 
Output and flow should remains the same.

We should also report the problem to ledisdb so we can use lua script again once they fix the problem upstream.

**Comment by muhamadazmy** [comment]
I think there is no need to have the lua script in ledis anyway, it was useful before when using redis since redis runs as an external process, unlike ledis which is impeded. What is the point of switching from go runtime, to lua then back to go, when all can be done in go.

Anyway, i will start working on the required changes for that.

**Comment by muhamadazmy** [comment]
I think we don't even need to keep the same data structure or queues name, since there is no single component that already depends on zero-os statistics yet.
