### ISSUE TITLE
cl.container.client(id) only accepts id as integer and fails when passed as string

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-core#358]
```...
nic = [{'type':'default'}, {'type': 'zerotier', 'id': ZEROTIER}]
job = cl.container.create('https://hub.gig.tech/gig-official-apps/ubuntu1604.flist', nics=nic, storage='ardb://hub.gig.tech:16379')
response= job.get(timeout=3660)
container_id = int(response.data)
c=cl.container.client(container_id)
c.info.nic()
```

**Comment by FastGeert** [comment]
I think accepting strings for the ```container.client``` method would be a good improvement because then at least the developer that uses the python client does not need to bother converting the id it got from the client into an integer to pass it again into the client.

Secondly I noticed that the str(response) is currently implemented the same as the repr(response). I would expect if I do str(response) I actually get response.data. If the command failed str(response) should throw a CommandFailedError(RuntimeError) that has a reference to the response object.

Doing all above will permit the developer to code like this:
```
cl.container.client(cl.container.create(...).get())
```

**Comment by grimpy** [comment]
The point is one should not do int(result.data) but do json.loads(result.data) instead.

**Comment by FastGeert** [comment]
result.data is always json?

Still does not defeat my arguing.
