### ISSUE TITLE
Names and tags for zero-os primitives

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-core#388]
We need a way to more easily identify primitives in zero-os when listing them via the api.

Primitives:
- processes
- containers
- processes in containers
- vms
- zerotier network

**Comment by muhamadazmy** [comment]
We can perfectly use job ID as a name, since the ID is actually chosen by the client. ID also is enforced to be unique by the zero-os and u can find a job (state, running, exists, etc...) by that ID. so no need for name for a job.

**Comment by muhamadazmy** [comment]
After a talk with @zaibon we agreed to the following:
- We don't need to introduce a new `name` flag for jobs/processes we can already leverage on the ID, for it's uniqueness and it can be chosen by the client (wasn't exposed) also that's what u receive back in all log messages.
- We can add names to containers and VMs, but they are really not needed (more than just metadata for the object) since containers coreX process doesn't produce any logs, same for VMs. BUT jobs inside containers do generate logs (same rules as core0 applies) log messages also holds the `core` number (0 for node, >0 for a container ID)
- We internally should handle libvirt events and log the machine state changes and log that up stream but on the libvirt job stream.

**Comment by zaibon** [comment]
>We can add names to containers and VMs, but they are really not needed (more than just metadata for the object) since containers coreX process doesn't produce any logs, same for VMs.

This is not true, 0-core should have some built-in monitoring for container and VM. That is something stop unexpectedly, it ouput an error message on the proper stderr. So the consumers of the stream can react on this.
