### ISSUE TITLE
A fake job_id subscription can stream another job 

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-core#477]
## Scenario 

1- Start a job for a long time that prints "Hi"
2- Subscribe to this job using job_id and subscriber_tag (ex: my-job-subscriber21)
3- Make another subscription with fake job_id but using same subscriber_tag that has been used in step 2 
## Actual Result 
- Step 3 subscription can stream step 2 subscription
## Expected Result
- Step 3 should throw an error that the job_id doesn't exist

![sscc1](https://user-images.githubusercontent.com/15011431/29607296-135ac952-87f1-11e7-9d6f-2864625a621c.png)

## Version
master @Revision: 8369d1a4417cefb4fc010e5d2a7a2c11b111a8c8

**Comment by muhamadazmy** [comment]
I have to explain what is the subscriber ID and how it works to explain why this bug won't be fixed because there is no way to fix it.

- When you start a `subscriber` it starts yet another job on the core0 that has (stream=True) by default and just copies another job (the watched job id) stream to its own stream (stdout, stderr). This allow us to have multiple subscriber that each get an exact copy of the main job that you want to watch.
- When u provide a subcriber ID it just sets the "subscriber" job ID. It's like starting any other job with a preset ID and not letting the client generate a new uuid for it. 
- 0-core will just reject that new job (it will never start a new job) since this means we will have conflicting job ids (or 2 jobs with the same id) which is not allowed.
- But to a subscriber that's not and issue, because it means u basically (when u call stream) will just copy the stream of the original subscriber (the one you first start with this given ID). And that's why the job ID was ignored. It's like if u rejoined the subscriber stream.
- The subscriber subsystem in 0-call never gets the second call because it was already rejected by 0-core from the start. No checks where done on the job id u were watching, and no way it can be done.
