### ISSUE TITLE
container.zerotier.list() doesn't gives client id

### ISSUE THREAD

**Issue by maxux** [zero-os/0-core#505]
I think there is a possible bug using the zerotier option.
When listing networks, the field `id` and `nwid` contains the same value.

I guess `id` should contains NodeId (aka MemberId) and not the NetworkId ? Otherwise, is there a way to get the MemberId ?

```
In [15]: x = cl.container.client(1)

In [16]: x.zerotier.list()
Out[16]: 
[{'allowDefault': False,
  'allowGlobal': False,
  'allowManaged': True,
  'assignedAddresses': [],
  'bridge': False,
  'broadcastEnabled': False,
  'dhcp': False,
  'id': '93afae59630d1169',
  'mac': '6a:68:dd:40:03:cf',
  'mtu': 2800,
  'name': '',
  'netconfRevision': 0,
  'nwid': '93afae59630d1169',
  'portDeviceName': 'zt0',
  'portError': 0,
  'routes': [],
  'status': 'ACCESS_DENIED',
  'type': 'PRIVATE'}]
```

**Comment by muhamadazmy** [comment]
@maxux 
That's so weird because code wise, we do not process or alter the data returned from zerotier-client. I checked and that's the exact data returned by the zerotier-cli when ran manually. Can we try a newer version of zerotier daemon to see if it returns what u need.

On the other hand, i think u still can use the mac address as a Nodeid, no ?

**Comment by muhamadazmy** [comment]
I will close this as won't fix, the data is as returned by the zt client. We also have the `x.zerotier.info()` call that returns the required data
