### ISSUE TITLE
Include 0-robot as primitives for 0-OS

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#574]
Concepts:
In production, we want to lock down the 0-core to only receives instruction from a 0-robot.
This 0-robot would need to be started automatically at boot and 0-core would only listen on localhost, so only the 0-robot container can talk to it.
The 0-robot is himself listening on the zerotier interface. 
In short, the public interface of the 0-os will be the 0-robot and not the 0-core.

This will imply that we need to move the logic of reserving a part of a disk for the 0-fs case into 0-core.
Cause we need to have a disk available to be able to deploy containers.

**Comment by muhamadazmy** [comment]
I don't get why do we need this? adding so many layers where just make things harder to debug. For example, if something went wrong there is noway u can investigate the node itself (since it only allow access from the localhost). Also you are hiding tons of primitives that gonna be difficult to abstract in zero-os.

Wouldn't it be easier, or better if core-0 itself remembered and maintained a state? I mean the system was designed from the beginning to be stateless, now we are introducing a state in the form of 0-robot! 

I agree with you on the `mount the cache` disk part, though

**Comment by zaibon** [comment]
This mode is not meant for development purpose so making debug harder is not a concern here.
Also having the 0-robot holding the state of the OS, this was the goal since the begining of 0-os, so nothing new here either.
Regaring hidding primitives I don't think that's a problem either, the only primitives we want to expose as for now are:
- zdb
- vm
- container
- 0-robot
see: https://github.com/zero-os/home/blob/master/specs/core_zrobot.md#implement-core-primitives

**Comment by zaibon** [comment]
For now blocked on the fact that I can't find a way to read the kernel parameters when auto starting a robot at boot. This is required to enable JWT authentication on the robot.

@muhamadazmy please advice

**Comment by muhamadazmy** [comment]
I tested it with both `privileged` and `unprivileged` containers and in both cases it was possible to read the `/proc/cmdline` file normally.

Can u please link me to the code that tries to do this read.
