### ISSUE TITLE
KVM reboot and shutdown doesn't seems to do anything

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#627]
I've created a VM on a node using the node robot and the [vm template](https://github.com/zero-os/0-templates/tree/master/templates/vm)

Then I tried to shutdown or reboot the vm, but nothing is happening when I call this methods.

**Comment by grimpy** [comment]
@zaibon the reboot and shutdown method instruct the os to do grafecull shutdown/reboot are you sure your os was properly running? Otherwise you need to use reset and destroy

**Comment by zaibon** [comment]
Yes it was running properly

**Comment by muhamadazmy** [comment]
@zaibon what VM image (or flist) not all systems handle ACPI signals.

**Comment by muhamadazmy** [comment]
@zaibon 
I used the ubuntu flist from hub. Calling shutdown or reboot does not affect the machine, but when I installed acpid on the machine, i was able to reboot it via reboot and shutdown calls. 

I will close this issue now since it's not core0 bug, the flist builder MUST install acpid (or any daemon to handle ACPI events).

**Comment by zaibon** [comment]
I'll reopen. Can we create a documentation that explain the minimum vital component that an bootable flist should have to work properly with all these call. 
So a full example/how to on how to create an flist for VM.

**Comment by muhamadazmy** [comment]
https://github.com/zero-os/0-core/tree/development/docs/vms#notes-on-vm-images
